version: revision {build}
environment:
  WEBHOOK_URL:
    secure: IUPo2N0bCejRvo0DxloThbwU/Q5tMeeXay7m/6quQXUH6XTbWYVvjQx/UXGMPoclB2N6nCnFM7QTqpwI8XMWoEKJdcM7Wn058ISffodpAGq2fcO4flZY7hJrcNCQnKDsRgstScQ4ENIBhY01YDH9BU8wv8SSzaPghtJEKmRl/Kc=
build_script:
- sh: >-
    cd "$APPVEYOR_BUILD_FOLDER" 

    ORIG=$(echo "$PWD")

    for d in */ ; do
        cd "$ORIG"
        [ "$d" = "build/" ] && continue

         DIRNAME=$(echo "$d" | tr -d '/')
         cd "$d"

         echo "$PWD"
         files=$(find . -type f -name "*.md" ! -name "_index.md" -print0 | sort -z -n | tr '\0' ' ')
         pandoc _index.md $files -s -f markdown_github+yaml_metadata_block+tex_math_single_backslash+grid_tables --pdf-engine pdflatex --highlight-style tango --variable graphics=yes --variable 'geometry:margin=0.7in' -M date:"$(date +'%d %B, %Y%n')" -o "../build/$DIRNAME.pdf"
    done



    cd "$ORIG"
on_success:
- pwsh: .\discord.ps1 success $env:WEBHOOK_URL
on_failure:
- pwsh: .\discord.ps1 failure $env:WEBHOOK_URL
...

