version: revision {build}
environment:
  WEBHOOK_URL:
    secure: IUPo2N0bCejRvo0DxloThbwU/Q5tMeeXay7m/6quQXUH6XTbWYVvjQx/UXGMPoclB2N6nCnFM7QTqpwI8XMWoEKJdcM7Wn058ISffodpAGq2fcO4flZY7hJrcNCQnKDsRgstScQ4ENIBhY01YDH9BU8wv8SSzaPghtJEKmRl/Kc=
  GH_TOKEN:
    secure: SfoqaWIvSYtUGYzLVyQWn6zD00m/usWTy6rq5v3iDgqa11k1Np9hD2FMJ8molt6z
build_script:
- sh: >-
    cd "$APPVEYOR_BUILD_FOLDER"


    ORIG=$(echo "$PWD")

    for d in */ ; do
        cd "$ORIG"
        [ "$d" = "build/" ] && continue

         DIRNAME=$(echo "$d" | tr -d '/')
         cd "$d"

         echo "$PWD"
         files=$(find . -type f -name "*.md" ! -name "_index.md" -print0 | sort -z -n | tr '\0' ' ')
         pandoc _index.md $files -s -f markdown_github+yaml_metadata_block+tex_math_single_backslash+grid_tables --pdf-engine pdflatex --highlight-style tango --variable graphics=yes --variable 'geometry:margin=0.7in' -M date:"$(date +'%d %B, %Y%n')" -o "../build/$DIRNAME.pdf"
    done

    cd "$ORIG"
deploy_script:
- pwsh: >-
    git config --global credential.helper store

    Add-Content "$HOME\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n"

    git config --global user.email "ci@tgrhavoc.me"

    git config --global user.name "CI on Olympus"

    git add build

    git commit -am "chore: build $($env:APPVEYOR_BUILD_VERSION) [skip ci]"

    git push origin HEAD:$($env:APPVEYOR_REPO_BRANCH)
on_success:
- pwsh: .\discord.ps1 success $env:WEBHOOK_URL
on_failure:
- pwsh: .\discord.ps1 failure $env:WEBHOOK_URL
...